#+SETUPFILE: css/level-0.orgcss
#+TITLE: Fedora 18 配置记录

Fedora 是 Red Hat 赞助的社区发行版本，倡导“FREEDOME, FRIENDS, FEATURES, FIRST”。其最新版本 Fedora 19 预计将在 2013.07.02 发布。

下面是 Fedora 18 体验过程中我遇到的问题。下面给出了解决方法，仅供参考。
  
* 配置
** 触摸板无法实现“点击”功能

  该问题解决方法与 [[http://tuhaihe.com/debian-wheezy-xfce-touchpad.html][Xfce 触摸板启动“点击”(Debian Wheezy)]] 一文中的解决方法一致。
  
** Adode flash 播放器

   因 Adobe Flash 插件不是自由和开源软件，所以无法预装在 Fedora 中。

  *解决方法[1]*

  1. 

  *X86\_64(64 位)*
  #+BEGIN_SRC shell
  sudo yum install http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm -y
  #+END_SRC

  *X86(32 位)*

  #+BEGIN_SRC shell
  sudo yum install http://linuxdownload.adobe.com/adobe-release/adobe-release-i386-1.0-1.noarch.rpm -y
  #+END_SRC

  2.导入 Adobe Flash 插件仓库 GPG 密钥并安装

  #+BEGIN_SRC shell
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux
sudo yum install flash-plugin -y
  #+END_SRC

** 多媒体编码解码器

  1.下载并安装 Free & Nonfree 仓库
     
  Free 软件仓库为开源软件仓库，Fedora 项目因为其他原因无法搭载；
  Nonfree 仓库主要存放非开源但可重新分发的软件。
     
  #+BEGIN_SRC shell
  # 适用于 Fedora14 到当前最新版本
  sudo 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
  #+END_SRC
     
  2.安装多媒体编解码器

  #+BEGIN_SRC shell
  sudo yum makecach #创建元数据缓存
  sudo yum install ffmpeg ffmpeg-libs gstreamer-ffmpeg xvidcore libdvdread libdvdnav lsdvd gstreamer-plugins-good gstreamer-plugins-bad gstreamer-plugins-ugly
  #+END_SRC

** 更多
   + 如果在安装过程中没有将创建的用户添加到管理组，则无法在命令前面使用 sudo。可用下面方法将当前用户添加至管理员组：

     #+BEGIN_SRC shell
     $ su #切换到 root 用户
     # echo 'fedora ALL=(ALL) ALL' >> /etc/sudoers #fedora为当前用户名
     #+END_SRC

* YUM 常用选项

  YUM 是基于 RPM 的软件包管理器，可用来更新、升级、安装或卸载软件包。

  命令格式： =yum [选项] 命令=

  #+CAPTION: 可用命令列表
| 可用命令  | 功能说明                         | apt “类似”命令（不完全对应）    |
| install   | 向系统中安装一个或多个软件包 | apt-get install                 |
| remove    | 从系统中移除一个或多个软件包 | apt-get remove                  |
| info      | 显示关于软件包或组的详细信息     | apt-cache show                  |
| makecache | 创建元数据缓存                   | apt-get update                  |
| reinstall | 重新安装一个包                   | apt-get install pkg --reinstall |
| search    | 在软件包详细信息中搜索指定字符串 | apt-cache search                |
| update    | 更新系统中的一个或多个软件包 | apt-get upgrade                 |
| upgrade   | 更新软件包同时考虑软件包取代关系 | apt-get dist-upgrade            |

[1] https://fedoraproject.org/wiki/Flash



